import 'package:flutter/material.dart';
import 'package:get/get.dart';

class AppTranslation extends Translations {
  static var locale = const Locale('en_US', '');
  static const fallbackLocale = Locale('en_US', '');
  static Map<String, Map<String, String>> translationsKeys = {
    "en_US": enUS,
    "de": de,
    "fr": fr
  };

  @override
  Map<String, Map<String, String>> get keys => translationsKeys;
  static void changeLocale(String lang) {
    locale = Locale(lang,'');
    Get.updateLocale(locale);
  }
}
// \w+\s*=\s*("[^"]*"(\s*[\n\r]+\s*".*?")*)

final Map<String, String> enUS = {
  'myDog': "MY DOG",
  'firstSliderHeading': "Train your Dog!",
  'firstSliderText':
      "Record training times, type of exercises, progress and performance evaluation. Recording of walks, length, location and additional annotations.",
  'choosePageHeading': "WHO ARE YOU?",
  'dogsParent': "DOG'S PARENT",
  'dogsExpert': "DOG'S EXPERT",
  'setProfileExpert': "Set a profile",
  'uploadYourPhoto': "Upload Your Photo",
  'yourName': "Your Name",
  'typeYourname': "Type your name here",
  'dateOfBirth': "Date of birth",
  'dateFormat': "DDMMYYYY",
  'yourMail': "Email",
  'typeYourMail': "Type your mail",
  'yourNumber': "Phone number",
  'typeNumber': "Type your phone number",
  'expertQualification': "Qualification",
  'typeQualification': "Tell your qualification",
  'expertSpeciality': "Speciality",
  'typeSpeciality': "Type your field",
  'yourPassword': "Password",
  'typePassword': "Type your password",
  'createButton': "Create",
  'hey': "Hey! ",
  'welcome': "Welcome to ",
  'appointments': "Appointments",
  'msgs': "Messages",
  'reminders': "Reminders",
  'seeProfile': "See profile",
  'seeAll': "See all",
  'addDog': "Add Dog",
  'upcommingAppointments': "Upcoming appointments",
  'approved': "Approved",
  'denied': "Denied",
  'dogName': "Dog name",
  'time': "00:00 PM",
  'home': "Home",
  'calendar': "Calendar",
  'settings': "Settings",
  'vaccination': "Vaccination",
  'medicine': "Medicine",
  'notifications': "Notifications",
  'manageDogs': "Manage dogs",
  'giveFeedback': "Give feedback",
  'termsOfUse': "Terms of use",
  'logout': "Logout",
  'deleteAccount': "Delete account",
  'appointDetail': "Appointment detail",
  'edit': "Edit",
  'appointType': "Appointment type",
  'pet': "Pet",
  'date': "Date",
  'notes': "Notes",
  'dogNameH': "Dog Name",
  'note':
      "After this exercise yor dog will pay more attention to you and your hands.",
  'releaseDogData': "Release your dog's data",
  'editRecord': "Edit Record",
  'shareRecord': "Share Record",
  'createRelease': "Create and Release your dog's data to an experts",
  'nameCapital': "DOG NAME",
  'data': "Data",
  'profile': "Profile",
  'dogsData': "Dog's Data",
  'healthData': "Health Data",
  'healthSub':
      "Add a appointment about of your dog's health and set  Reminder about the vaccination or grooming session.",
  'appAppoint': "Add Appointments",
  'exerciseExpert': "Exercises & Experts",
  'feedManage': "Feed management",
  'safetyEmergency': "Safety and Emergency",
  'gotoCommunity': "Go to Community",
  'kg': "00:00 KG",
  'weight': "Weight (Kg)",
  'filesFromExpert': "Released files form expert",
  'releaseFiles': "Released file form expert after appointment",
  'trainingStreak': "Training Report",
  'currentStreak': "Current streak",
  'longestStreak': "Longest streak",
  'timeTrained': "Time trained",
  'days0': "0 Days",
  'days1': "1 Days",
  'timeStamp': "00:07:01",
  'microChipNum': "Microchip number",
  'gender': "Gender",
  'breed': "Breed",
  'editProfile': "Edit profile",
  'selectExpert': "Select Experts",
  'whoRU': "Who are you",
  'lookingFor': "Looking for?",
  'trainExpert': "Training expert",
  'physioExpert': "Physiotherapists",
  'nutriExpert': "Nutritionists",
  'vetExpert': "Veterinarians",
  'otherExpert': "Other",
  'selectReport': "Select Report",
  'whichRU': "Which Report do you",
  'wantRelease': "Want to release?",
  'trainReport': "General Report",
  'physioReport': "Diet Report",
  'nutriReport': "Training Report",
  'share': "Share",
  'selectExpertSingle': "Select Expert",
  'expertAbout':
      "A certified dog trainer with years of professional experience, a founder of the Academy of Modern Training for Dogs and Families.",
  'trainingExpert': "Training Expert",
  'healthExpert': "Health Expert",
  'chat': "Chat",
  'relReport': "Release Report",
  'releasedReport': "Released Report",
  'seeProfileBtn': "See Profile",
  'endSharing': "End Sharing",
  'wantToEdit': "WANT TO EDIT?",
  'dogBehaviour': "Dog's Behavior",
  'hintRecentDisease': "Type your dog's recent disease if any",
  'hintDogBehaviour': "Chose your dog's behaviour",
  'photo': "Photo",
  'files': "Files",
  'save': "Save",
  'requests': "Requests/Appointments",
  'underCare': "Dogs under your care",
  'requested': "Requested",
  'detail': "Detail",
  'reject': "Reject",
  'approve': "Approve",
  'completed': "Completed",
  'createFile': "Create Dog's File",
  'informParent':
      "Create a file of dog's appointment detail to inform this dog's parent.",
  'vaccinationReport': "Vaccination Report",
  'typeVaccine': "Type of vaccine",
  'selectVaccine': "Select type of vaccine here",
  'doze': "Doze",
  'typeNotes': "Type some notes here",
  'sendNoti': "Send notification to parent",
  'release': "Release",
  'typeDogName': "Type dog's name here",
  'timeHeading': "Time",
  'seePatients': "See Patients",
  'makeAnnouncement': "Make Announcement",
  'trainingData': "Training Data",
  'seeTrainingFile': "See Training File",
  'excercise': "Exercise",
  'handFeeding': "Hand Feeding",
  'title': "Title",
  'description': "Description",
  'giveTitle': "Give title",
  'visibleToParent': "Visible to parent",
  'addComment': "Add Comment",
  'patientFiles': "Patient files",
  'symptoms': "Symptoms",
  'antiparasitic': "Anti parasitic",
  'vetVisit': "Vet Visit",
  'seeAllFiles': "See all patient files which are released from your expert.",
  'next': "Next",
  'lang': "Language",
  'sliderHeading2': "Maintain health data!",
  'sliderHeading3': "Talk to experts",
  'slidertxt2':
      "See Record of past and current illnesses, medication administrations, allergies and surgeries.",
  'slidertxt3':
      "Search and contact with dog trainers, dog physiotherapists, dog nutritionists and veterinarians.",
  'selectLang': "Select language",
  'german': "German",
  'english': "English",
  'french': "French",
  'signupTxt':
      "Almost there! Get the most out of MY DOG by  creating an account. Track your training progress, participate in the challenges, meet other dog parents, and more!",
  'loginORsignup': "Login or signup",
  'login': "Login",
  'google': "Continue with google",
  'mail': "Sign up with email",
  'forgetPass': "Forgot password?",
  'typeMail': "Type your email",
  'typePass': "Type your password",
  'alreadyAccount': "Already have an account?",
  'agreeing': "By creating an account you agree to MY DOG's",
  'policy': "Privacy policy and Term of use",
  'or': "OR",
  'setProfile': "Set a profile for your Dog",
  'uploadDog': "Upload Dog's Photo",
  'dogsName': "Dog's name",
  'neutered': "Neutered",
  'color': "Color",
  'male': "Male",
  'female': "Female",
  'typeGender': "Describe gender of your dog",
  'typeChipNumber': "Tell your dog's chip number",
  'typeColor': "What type of color your dog have?",
  'selectBreed': "Select your dog's breed here",
  'typeWeight': "How much weight your dog have?",
  'createTraining': "Create Training",
  'uploadPhoto': "Upload Photo",
  'trainingTitle': "Training Title",
  'giveTraining': "Give this Training a tilte",
  'shortNote': "Type a short note",
  'trainingNote': "Note",
  'listDown': "List down the needed equipment",
  'neededEquipment': "Needed Equipment",
  'trainingLevel': "Training level",
  'eligibility': "Eligibility",
  'category': "Category",
  'hintEligibilty': "Specify the eligibility for this training",
  'trainLength': "Training Length",
  'uploadFiles': "Upload Files",
  'media': "Media",
  'post': "Post",
  'material': "Training Material",
  'general': "General",
  'dayByday': "Day by Day",
  'giveDescription': "Give description",
  'exercises': "Exercises",
  'games': "Games",
  'goodManners': "Good Manners",
  'trainingPrograms': "Training Programs",
  'addTraining': "Add Training Program",
  'stopBitting': "Stop Biting",
  'theory': "Theory",
  'payAttention': "Pay Attention",
  'addExercise': "Add Exercise",
  'walk': "Walk",
  'addFood': "Add Food",
  'dietPlan': "Diet plan",
  'foodManagement': "Food management",
  'dailFoodReminders': "Daily Food Reminders",
  'planDogExperts': "Plans by your dog's experts",
  'feedNote':
      "Add and manage your dogs daily food timing, create food plans, and diet plans.",
  'handFeedNote':
      "After this exercise yor dog will pay more attention to you and your hands. Get your dog’s attention and show them some super tasty food or treats in your hand.",
  'payAttenNote':
      "Teach your dog to pay attention to you and listen to you whenever you call him/her.",
  'bittingNote':
      "Teach your dog to control their impulses, excitement, and the urge to wrap their jaw around anything.",
  'dietNote':
      "Teach your dog to control their impulses, excitement, and the urge to wrap their jaw around anything.",
  'morningFood': "Morning Food",
  'foodName': "Food name",
  'eveningFood': "Evening Food",
  'typeFood': "Type food name here",
  'foodOutside': "Food outside",
  'reminderNoti': "Reminder Notification",
  'day': "Day",
  'learnTennis': "You can learn all about tennis.",
  'articles': "Articles",
  'timing': "Timing",
  'duration': "Duration",
  'calories': "Calories(kcal)",
  'createFoodorDiet': "Create Food/Diet Plan",
  'createPlan': "Create Plan",
  'planTitle': "Plan title",
  'startDate': "Start date",
  'endDate': "End date",
  'givePlanTitle': "Give this plan title",
  'createTimeTable': "Create time table",
  'createDetailedTb': "Create detailed time table fot this plan",
  'seeEmergencyNum': "See Emergency Numbers",
  'missingFound': "Missing & Found",
  'missingNote':
      "Find your missing dog or report a found dog to help someone reunite with their furry companion.",
  'addReport': "Add Report",
  'impInstructions': "Important Instructions",
  'emergencyCases': "What you have to do in emergency cases ",
  'inCaseEmergency': "In case of an emergency",
  'noteEmergency':
      "Teach your dog to control their impulses, excitement, and the urge to wrap their jaw around anything.",
  'missingDog': "Missing Dog",
  'lostDate': "Lost Date",
  'lostAddress': "Lost Address",
  'foundedDog': "Founded Dog",
  'emergencyNums': "Emergency Numbers",
  'search': "Search",
  'addNum': "Add Number",
  'upload': "Upload",
  'typeName': "Type name here",
  'typeNum': "Add phone number here",
  'name': "Name",
  'emergencyReport': "Emergency Report",
  'whatYou': "What do you",
  'wantTo': "Want to report?",
  'dogBait': "Dog Bait",
  'missingReport': "Missing Report",
  'foundOne': "Found One",
  'warnParents': "Warn parents about",
  'theDanger': "The danger",
  'baitLocation': "Bait loction",
  'typeBaitLocation': "Type bait location",
  'addBaitLocation': "Add bait location on map",
  'sendNotiAll': "Send notification to all",
  'mapView': "Map View",
  'missingDogs': "Missing Dogs",
  'foundedDogs': "Founded Dogs",
  'createReport': "Create Report",
  'age': "Age",
  'parentsData': "Parent's Data",
  'yourAddress': "Your addresss",
  'typeAddress': "Type addresss here",
  'foundDate': "Found date",
  'multiplePhotos': "Upload multiple photos",
  'missingDogProfile': "Missing Dog",
  'seeMap': "See map",
  'chatParent': "Chat with parent",
  'shareDog': "Share Dog's Profile",
  'address': "Address",
  'addressHere': "Address here",
  'parentName': "Parent name",
  'contactInfo': "Contact Information",
  'somePhotos': "Some photos",
  'comments': "Comments",
  'commentTitle': "Comment Title",
  'management': "Management",
  'sendArchive': "Send to archive",
  'dontShow': "Do not show in dashboard",
  'deathDate': "Date of Death",
  'deleteDog': "Delete dog",
  'dogDied': "Dog died",
  'reason': "Reason",
  'typeReason': "Type reason here",
  'otherReason': "Other reason",
  'selectReason': "Select reason",
  'whyReason': "Why do you want to delete your dog?",
  'lostNote':
      "Hy! I lost my pet dog please help me to find my beloved dog. Thank you",
  'missNote':
      "Hy! I found a wandering dog please contact with if someone recognize him",
  'community': "Community",
  'chats': "Chats",
  'groups': "Groups",
  'connectExperts': "Connect with experts",
  'now': "now",
  'bestWay': "Best way to train dog",
  'addChat': "Add Chat",
  'online': "Online",
  'message': "message",
  'addNewGrps': "Add new group by creating or finding groups",
  'newGroups': "New groups",
  'findGroup': "Find group",
  'createGroup': "Create group",
  'eventCalendar': "Event Calendar",
  'addReminder': "Add Reminder",
  'reminderName': "Reminder name",
  'repeat': "Repeat",
  'sett': "Set",
  'typeTime': "Type time",
  'walkRouts': "Walk & Routs",
  'training': "Training",
  'experts': "Experts",
  'findExpert': "Find an expert",
  'availExperts': "Check available experts and contact with them.",
  'find': "Find",
  'yourDogExperts': "Your Dog's Experts",
  'addManual': "Add Manually",
  'distance': "Distance(km)",
  'totalDistance': "Total distance",
  'totalSteps': "Total steps",
  'minutes': "Minutes",
  'steps': "Steps",
  'recentWalk': "Recent walk",
  'addRecordManually': "Add record manually",
  'swipe': "Swipe to record new walk",
  'walkRecord': "Walk Record",
  'walkComplete': "Walk Complete",
  'stops': "Stops",
  'pause': "Pause",
  'complete': "Complete",
  'comment': "Comment",
  'dogCondition': "Dog's Condition",
  'walkingTrack': "Walking track",
  'forest': "Forest",
  'weather': "How was the weather?",
  'warm': "Warm",
  'searchByName': "Search by name",
  'sendInvite': "Send an invitation",
  'sendLocally': "Send invitation locally via communication apps or via number",
  'invite': "Send invitation",
  'tutorial': "Tutorial",
  'completeExercise': "Complete Exercise",
  'details': "Details",
  'easy': "Easy",
  'trainingLength': "Training length",
  'equipment': "Equipment",
  'editExercise': "Edit Exercise",
  'highFive': "High five",
  'trainingNotes':
      "After this exercise yor dog will pay more attention to you and your hands.",
  'trainingProgram': "Training Program",
  'preparedByExpert': "Prepared by expert",
  'noAction': "No action",
  'releasedReports': "Released Reports",
  'expertProfile': "Expert Profile",
  'sharedData': "Shared data",
  'totalTrainings': "Total trainings",
  'saveRecord': "Save Record",
  'caseOfEmergency': "Case of an emergency",
  'success': "Success",
  'loginMsg': "Now you can login",
  'error': "Error",
  'yes': "Yes",
  'no': "No",
  'addColor': "Add Color",
  'neuteredHint': "Your dog is neutered or not",
  'pickColor': "Pick a color",
  'ok': "Ok",
  'more': "More",
  'titleSelectBreed': "Select Breed",
  'dogAdded': "Added successfully",
  'dogdeleted': "Deleted successfully",
  'fillAll': "Please fill all fields",
  'none': "None",
  'never': "Never",
  'monday': "Monday",
  'tuesday': "Tuesday",
  'wednesday': "Wednesday",
  'thursday': "Thursday",
  'friday': "Friday",
  'saturday': "Saturday",
  'sunday': "Sunday",
  'everyday': "Everyday",
  'weekdays': "Weekdays",
  'weekend': "Weekend",
  'setReminder': "Set Reminder",
  'signup': "Signup",
  'request': "Request",
  'noAccount': "Don't have an account?",
  'incorrect': "Email or password is incorrect",
  'selectImage': "Please select image",
  'yourDoc': "Your Doctor",
  'selectDoc': "Select Doctor",
  'reasonAppointment': "Reason of appointment",
  'timeTable': "Time Table",
  'morning': "Morning",
  'evening': "Evening",
  'midday': "Midday",
  'quantity': "Quantity(grams)",
  'selectRightTime': "Please select right time",
  'morningTime': "9am to 12pm",
  'midTime': "12pm to 6pm",
  'eveningTime': "6pm to 12am",
  'addEvent': "Add event",
  'subTitle': "Subtitle",
  'giveSubTitle': "Give subtitle",
  'location': "Location",
  'addLocation': "Add venue",
};
final Map<String, String> fr = {
 'myDog': "MY DOG",
  'firstSliderHeading': "Entraînez votre chien!",
  'firstSliderText':
      "Enregistrez les horaires d'entraînement, le type d'exercices, les progrès et l'évaluation des performances. Enregistrement des promenades, de la durée, de l'emplacement et des annotations supplémentaires.",
  'choosePageHeading': "QUI ÊTES-VOUS?",
  'dogsParent': "PARENT DU CHIEN",
  'dogsExpert': "EXPERT DU CHIEN",
  'setProfileExpert': "Définir un profil",
  'uploadYourPhoto': "Téléchargez votre photo",
  'yourName': "Votre nom",
  'typeYourname': "Tapez votre nom ici",
  'dateOfBirth': "Date de naissance",
  'dateFormat': "JJMMAAAA",
  'yourMail': "Email",
  'typeYourMail': "Tapez votre email",
  'yourNumber': "Numéro de téléphone",
  'typeNumber': "Tapez votre numéro de téléphone",
  'expertQualification': "Qualification",
  'typeQualification': "Indiquez votre qualification",
  'expertSpeciality': "Spécialité",
  'typeSpeciality': "Indiquez votre domaine",
  'yourPassword': "Mot de passe",
  'typePassword': "Tapez votre mot de passe",
  'createButton': "Créer",
  'hey': "Bonjour! ",
  'welcome': "Bienvenue à ",
  'appointments': "Rendez-vous",
  'msgs': "Messages",
  'reminders': "Rappels",
  'seeProfile': "Voir le profil",
  'seeAll': "Voir tout",
  'addDog': "Ajouter un chien",
  'upcommingAppointments': "Rendez-vous à venir",
  'approved': "Approuvé",
  'denied': "Refusé",
  'dogName': "Nom du chien",
  'time': "00:00 PM",
  'home': "Accueil",
  'calendar': "Calendrier",
  'settings': "Paramètres",
  'vaccination': "Vaccination",
  'medicine': "Médicament",
  'notifications': "Notifications",
  'manageDogs': "Gérer les chiens",
  'giveFeedback': "Donner un feedback",
  'termsOfUse': "Conditions d'utilisation",
  'logout': "Déconnexion",
  'deleteAccount': "Supprimer le compte",
  'appointDetail': "Détail du rendez-vous",
  'edit': "Modifier",
  'appointType': "Type de rendez-vous",
  'pet': "Animal de compagnie",
  'date': "Date",
  'notes': "Notes",
  'dogNameH': "Nom du chien",
  'note':
      "Après cet exercice, votre chien prêtera plus d'attention à vous et à vos mains.",
  'releaseDogData': "Publier les données de votre chien",
  'editRecord': "Modifier l'enregistrement",
  'shareRecord': "Partager l'enregistrement",
  'createRelease':
      "Créez et publiez les données de votre chien auprès d'experts",
  'nameCapital': "NOM DU CHIEN",
  'data': "Données",
  'profile': "Profil",
  'dogsData': "Données du chien",
  'healthData': "Données de santé",
  'healthSub':
      "Ajoutez un rendez-vous concernant la santé de votre chien et définissez un rappel concernant la vaccination ou la séance de toilettage.",
  'appAppoint': "Ajouter des rendez-vous",
  'exerciseExpert': "Exercices et experts",
  'feedManage': "Gestion de l'alimentation",
  'safetyEmergency': "Sécurité et Urgence",
  'gotoCommunity': "Aller à la communauté",
  'kg': "00:00 KG",
  'weight': "Poids (Kg)",
  'filesFromExpert': "Fichiers publiés par l'expert",
  'releaseFiles': "Fichiers publiés par l'expert après le rendez-vous",
  'trainingStreak': "Rapport d'entraînement",
  'currentStreak': "Série actuelle",
  'longestStreak': "Série la plus longue",
  'timeTrained': "Temps d'entraînement",
  'days0': "0 jours",
  'days1': "1 jour",
  'timeStamp': "00:07:01",
  'microChipNum': "Numéro de micro-puce",
  'gender': "Genre",
  'breed': "Race",
  'editProfile': "Modifier le profil",
  'selectExpert': "Sélectionner des experts",
  'whoRU': "Qui êtes-vous",
  'lookingFor': "À la recherche de?",
  'trainExpert': "Expert en entraînement",
  'physioExpert': "Physiothérapeutes",
  'nutriExpert': "Nutritionnistes",
  'vetExpert': "Vétérinaires",
  'otherExpert': "Autre",
  'selectReport': "Sélectionner un rapport",
  'whichRU': "Quel rapport voulez-vous",
  'wantRelease': "Voulez-vous publier?",
  'trainReport': "Rapport général",
  'physioReport': "Rapport diététique",
  'nutriReport': "Rapport d'entraînement",
  'share': "Partager",
  'selectExpertSingle': "Sélectionner un expert",
  'expertAbout':
      "Un dresseur de chiens certifié avec des années d'expérience professionnelle, fondateur de l'Académie de Dressage Moderne pour Chiens et Familles.",
  'trainingExpert': "Expert en Entraînement",
  'healthExpert': "Expert en Santé",
  'chat': "Chat",
  'relReport': "Publier le rapport",
  'releasedReport': "Rapport publié",
  'seeProfileBtn': "Voir le profil",
  'endSharing': "Fin du partage",
  'wantToEdit': "VOULEZ-VOUS MODIFIER?",
  'dogBehaviour': "Comportement du chien",
  'hintRecentDisease':
      "Indiquez la récente maladie de votre chien s'il y en a une",
  'hintDogBehaviour': "Choisissez le comportement de votre chien",
  'photo': "Photo",
  'files': "Fichiers",
  'save': "Enregistrer",
  'requests': "Demandes/Rendez-vous",
  'underCare': "Chiens sous votre garde",
  'requested': "Demandé",
  'detail': "Détail",
  'reject': "Rejeter",
  'approve': "Approuver",
  'completed': "Terminé",
  'createFile': "Créer le dossier du chien",
  'informParent':
      "Créez un dossier détaillé du rendez-vous du chien pour informer les parents de ce chien.",
  'vaccinationReport': "Rapport de vaccination",
  'typeVaccine': "Type de vaccin",
  'selectVaccine': "Sélectionnez le type de vaccin ici",
  'doze': "Dose",
  'typeNotes': "Tapez quelques notes ici",
  'sendNoti': "Envoyer une notification aux parents",
  'release': "Publier",
  'typeDogName': "Tapez le nom du chien ici",
  'timeHeading': "Heure",
  'seePatients': "Voir les patients",
  'makeAnnouncement': "Faire une annonce",
  'trainingData': "Données d'entraînement",
  'seeTrainingFile': "Voir le fichier d'entraînement",
  'excercise': "Exercice",
  'handFeeding': "Nourrissage à la main",
  'title': "Titre",
  'description': "Description",
  'giveTitle': "Donner un titre",
  'visibleToParent': "Visible pour les parents",
  'addComment': "Ajouter un commentaire",
  'patientFiles': "Fichiers du patient",
  'symptoms': "Symptômes",
  'antiparasitic': "Antiparasitaire",
  'vetVisit': "Visite chez le vétérinaire",
  'seeAllFiles':
      "Voir tous les fichiers de patients qui sont publiés par votre expert.",
  'next': "Suivant",
  'lang': "Langue",
  'sliderHeading2': "Maintenez les données de santé!",
  'sliderHeading3': "Parlez à des experts",
  'slidertxt2':
      "Consultez les enregistrements des maladies passées et actuelles, des administrations de médicaments, des allergies et des interventions chirurgicales.",
  'slidertxt3':
      "Recherchez et contactez des dresseurs de chiens, des physiothérapeutes pour chiens, des nutritionnistes pour chiens et des vétérinaires.",
  'selectLang': "Sélectionnez la langue",
  'german': "Allemand",
  'english': "Anglais",
  'french': "Français",
  'signupTxt':
      "Presque là! Obtenez le meilleur de MON CHIEN en créant un compte. Suivez vos progrès d'entraînement, participez aux défis, rencontrez d'autres parents de chiens, et plus encore!",
  'loginORsignup': "Connexion ou inscription",
  'login': "Connexion",
  'google': "Continuer avec Google",
  'mail': "Inscription par e-mail",
  'forgetPass': "Mot de passe oublié?",
  'typeMail': "Tapez votre e-mail",
  'typePass': "Tapez votre mot de passe",
  'alreadyAccount': "Vous avez déjà un compte?",
  'agreeing':
      "En créant un compte, vous acceptez la politique de confidentialité et les conditions d'utilisation de MON CHIEN",
  'policy': "Politique de confidentialité et Conditions d'utilisation",
  'or': "OU",
  'setProfile': "Définir un profil pour votre chien",
  'uploadDog': "Télécharger la photo du chien",
  'dogsName': "Nom du chien",
  'neutered': "Stérilisé",
  'color': "Couleur",
  'male': "Mâle",
  'female': "Femelle",
  'typeGender': "Décrivez le sexe de votre chien",
  'typeChipNumber': "Indiquez le numéro de puce de votre chien",
  'typeColor': "Quel type de couleur a votre chien?",
  'selectBreed': "Sélectionnez la race de votre chien ici",
  'typeWeight': "Quel poids pèse votre chien?",
  'createTraining': "Créer un entraînement",
  'uploadPhoto': "Télécharger la photo",
  'trainingTitle': "Titre de l'entraînement",
  'giveTraining': "Donnez un titre à cet entraînement",
  'shortNote': "Tapez une courte note",
  'trainingNote': "Note",
  'listDown': "Énumérez l'équipement nécessaire",
  'neededEquipment': "Équipement nécessaire",
  'trainingLevel': "Niveau d'entraînement",
  'eligibility': "Éligibilité",
  'category': "Catégorie",
  'hintEligibilty': "Spécifiez l'éligibilité pour cet entraînement",
  'trainLength': "Durée de l'entraînement",
  'uploadFiles': "Télécharger des fichiers",
  'media': "Médias",
  'post': "Publier",
  'material': "Matériel d'entraînement",
  'general': "Général",
  'dayByday': "Jour par jour",
  'giveDescription': "Donner une description",
  'exercises': "Exercices",
  'games': "Jeux",
  'goodManners': "Bonne conduite",
  'trainingPrograms': "Programmes d'entraînement",
  'addTraining': "Ajouter un programme d'entraînement",
  'stopBitting': "Arrêtez de mordre",
  'theory': "Théorie",
  'payAttention': "Portez attention",
  'addExercise': "Ajouter un exercice",
  'walk': "Promenade",
  'addFood': "Ajouter de la nourriture",
  'dietPlan': "Plan alimentaire",
  'foodManagement': "Gestion alimentaire",
  'dailFoodReminders': "Rappels alimentaires quotidiens",
  'planDogExperts': "Plans par les experts de votre chien",
  'feedNote':
      "Ajoutez et gérez les horaires alimentaires quotidiens de vos chiens, créez des plans alimentaires et des régimes alimentaires.",
  'handFeedNote':
      "Après cet exercice, votre chien prêtera plus attention à vous et à vos mains. Attirez l'attention de votre chien et montrez-lui de la nourriture ou des friandises super délicieuses dans votre main.",
  'payAttenNote':
      "Apprenez à votre chien à vous prêter attention et à vous écouter chaque fois que vous l'appelez.",
  'bittingNote':
      "Apprenez à votre chien à contrôler ses impulsions, son excitation et l'envie d'envelopper sa mâchoire autour de n'importe quoi.",
  'dietNote':
      "Apprenez à votre chien à contrôler ses impulsions, son excitation et l'envie d'envelopper sa mâchoire autour de n'importe quoi.",
  'morningFood': "Nourriture du matin",
  'foodName': "Nom de la nourriture",
  'eveningFood': "Nourriture du soir",
  'typeFood': "Tapez le nom de la nourriture ici",
  'foodOutside': "Nourriture à l'extérieur",
  'reminderNoti': "Notification de rappel",
  'day': "Jour",
  'learnTennis': "Vous pouvez tout apprendre sur le tennis.",
  'articles': "Articles",
  'timing': "Timing",
  'duration': "Durée",
  'calories': "Calories (kcal)",
  'createFoodorDiet': "Créer un plan alimentaire / diététique",
  'createPlan': "Créer un plan",
  'planTitle': "Titre du plan",
  'startDate': "Date de début",
  'endDate': "Date de fin",
  'givePlanTitle': "Donnez ce titre de plan",
  'createTimeTable': "Créer un emploi du temps",
  'createDetailedTb': "Créer un emploi du temps détaillé pour ce plan",
  'seeEmergencyNum': "Voir les numéros d'urgence",
  'missingFound': "Perdu et Trouvé",
  'missingNote':
      "Trouvez votre chien perdu ou signalez un chien trouvé pour aider quelqu'un à retrouver son compagnon à quatre pattes.",
  'addReport': "Ajouter un rapport",
  'impInstructions': "Instructions importantes",
  'emergencyCases': "Que devez-vous faire en cas d'urgence",
  'inCaseEmergency': "En cas d'urgence",
  'noteEmergency':
      "Apprenez à votre chien à contrôler ses impulsions, son excitation et l'envie d'envelopper sa mâchoire autour de n'importe quoi.",
  'missingDog': "Chien perdu",
  'lostDate': "Date de perte",
  'lostAddress': "Adresse perdue",
  'foundedDog': "Chien trouvé",
  'emergencyNums': "Numéros d'urgence",
  'search': "Rechercher",
  'addNum': "Ajouter un numéro",
  'upload': "Télécharger",
  'typeName': "Tapez le nom ici",
  'typeNum': "Ajouter un numéro de téléphone ici",
  'name': "Nom",
  'emergencyReport': "Rapport d'urgence",
  'whatYou': "Que voulez-vous",
  'wantTo': "Signaler?",
  'dogBait': "Appât pour chien",
  'missingReport': "Rapport de disparition",
  'foundOne': "Trouvé",
  'warnParents': "Avertir les parents du",
  'theDanger': "Le danger",
  'baitLocation': "Emplacement de l'appât",
  'typeBaitLocation': "Tapez l'emplacement de l'appât",
  'addBaitLocation': "Ajouter l'emplacement de l'appât sur la carte",
  'sendNotiAll': "Envoyer une notification à tous",
  'mapView': "Vue de la carte",
  'missingDogs': "Chiens perdus",
  'foundedDogs': "Chiens trouvés",
  'createReport': "Créer un rapport",
  'age': "Âge",
  'parentsData': "Données des parents",
  'yourAddress': "Votre adresse",
  'typeAddress': "Tapez l'adresse ici",
  'foundDate': "Date de trouvaille",
  'multiplePhotos': "Télécharger plusieurs photos",
  'missingDogProfile': "Chien perdu",
  'seeMap': "Voir la carte",
  'chatParent': "Discuter avec les parents",
  'shareDog': "Partager le profil du chien",
  'address': "Adresse",
  'addressHere': "Adresse ici",
  'parentName': "Nom des parents",
  'contactInfo': "Informations de contact",
  'somePhotos': "Quelques photos",
  'comments': "Commentaires",
  'commentTitle': "Titre du commentaire",
  'management': "Gestion",
  'sendArchive': "Envoyer aux archives",
  'dontShow': "Ne pas afficher dans le tableau de bord",
  'deathDate': "Date de décès",
  'deleteDog': "Supprimer le chien",
  'dogDied': "Chien décédé",
  'reason': "Raison",
  'typeReason': "Tapez la raison ici",
  'otherReason': "Autre raison",
  'selectReason': "Sélectionner la raison",
  'whyReason': "Pourquoi voulez-vous supprimer votre chien?",
  'lostNote':
      "Salut! J'ai perdu mon chien bien-aimé. S'il vous plaît, aidez-moi à le retrouver. Merci",
  'missNote':
      "Salut! J'ai trouvé un chien errant. Veuillez me contacter si quelqu'un le reconnaît.",
  'community': "Communauté",
  'chats': "Chats",
  'groups': "Groupes",
  'connectExperts': "Se connecter avec des experts",
  'now': "maintenant",
  'bestWay': "Meilleure façon de dresser un chien",
  'addChat': "Ajouter un Chat",
  'online': "En ligne",
  'message': "message",
  'addNewGrps': "Ajouter un nouveau groupe en le créant ou en le trouvant",
  'newGroups': "Nouveaux groupes",
  'findGroup': "Trouver un groupe",
  'createGroup': "Créer un groupe",
  'eventCalendar': "Calendrier d'événements",
  'addReminder': "Ajouter un rappel",
  'reminderName': "Nom du rappel",
  'repeat': "Répéter",
  'sett': "Réglé",
  'typeTime': "Tapez l'heure",
  'walkRouts': "Promenade & Parcours",
  'training': "Entraînement",
  'experts': "Experts",
  'findExpert': "Trouver un expert",
  'availExperts': "Vérifiez les experts disponibles et contactez-les.",
  'find': "Trouver",
  'yourDogExperts': "Les Experts de Votre Chien",
  'addManual': "Ajouter Manuellement",
  'distance': "Distance (km)",
  'totalDistance': "Distance totale",
  'totalSteps': "Pas totaux",
  'minutes': "Minutes",
  'steps': "Pas",
  'recentWalk': "Promenade récente",
  'addRecordManually': "Ajouter un enregistrement manuellement",
  'swipe': "Balayez pour enregistrer une nouvelle promenade",
  'walkRecord': "Enregistrement de la promenade",
  'walkComplete': "Promenade terminée",
  'stops': "Arrêts",
  'pause': "Pause",
  'complete': "Complet",
  'comment': "Commentaire",
  'dogCondition': "Condition du chien",
  'walkingTrack': "Parcours de marche",
  'forest': "Forêt",
  'weather': "Comment était le temps?",
  'warm': "Chaud",
  'searchByName': "Rechercher par nom",
  'sendInvite': "Envoyer une invitation",
  'sendLocally':
      "Envoyer une invitation localement via des applications de communication ou via un numéro",
  'invite': "Envoyer une invitation",
  'tutorial': "Didacticiel",
  'completeExercise': "Exercice terminé",
  'details': "Détails",
  'easy': "Facile",
  'trainingLength': "Durée de l'entraînement",
  'equipment': "Équipement",
  'editExercise': "Modifier l'exercice",
  'highFive': "Cinq haut",
  'trainingNotes':
      "Après cet exercice, votre chien prêtera plus attention à vous et à vos mains.",
  'trainingProgram': "Programme d'entraînement",
  'preparedByExpert': "Préparé par un expert",
  'noAction': "Aucune action",
  'releasedReports': "Rapports publiés",
  'expertProfile': "Profil de l'expert",
  'sharedData': "Données partagées",
  'totalTrainings': "Entraînements totaux",
  'saveRecord': "Enregistrer l'enregistrement",
  'caseOfEmergency': "En cas d'urgence",
  'success': "Succès",
  'loginMsg': "Maintenant, vous pouvez vous connecter",
  'error': "Erreur",
  'yes': "Oui",
  'no': "Non",
  'addColor': "Ajouter une couleur",
  'neuteredHint': "Votre chien est-il castré ou non",
  'pickColor': "Choisissez une couleur",
  'ok': "D'accord",
  'more': "Plus",
  'titleSelectBreed': "Sélectionner la race",
  'dogAdded': "Ajouté avec succès",
  'dogdeleted': "Supprimé avec succès",
  'fillAll': "Veuillez remplir tous les champs",
  'none': "Aucun",
  'never': "Jamais",
  'monday': "Lundi",
  'tuesday': "Mardi",
  'wednesday': "Mercredi",
  'thursday': "Jeudi",
  'friday': "Vendredi",
  'saturday': "Samedi",
  'sunday': "Dimanche",
  'everyday': "Tous les jours",
  'weekdays': "Jours de semaine",
  'weekend': "Week-end",
  'setReminder': "Définir un rappel",
  'signup': "Inscription",
  'request': "Demande",
  'noAccount': "Vous n'avez pas de compte?",
  'incorrect': "L'e-mail ou le mot de passe est incorrect",
  'selectImage': "Veuillez sélectionner une image",
  'yourDoc': "Votre médecin",
  'selectDoc': "Sélectionner un médecin",
  'reasonAppointment': "Raison du rendez-vous",
  'timeTable': "Emploi du temps",
  'morning': "Matin",
  'evening': "Soir",
  'midday': "Midi",
  'quantity': "Quantité(grammes)",
  'selectRightTime': "Veuillez sélectionner le bon moment",
  'morningTime': "9h à 12h",
  'midTime': "12h à 18h",
  'eveningTime': "18h à minuit",
  'addEvent': "Ajouter un événement",
  'subTitle': "Sous-titre",
  'giveSubTitle': "Donner un sous-titre",
  'location': "Emplacement",
  'addLocation': "Ajouter un lieu",
};
final Map<String, String> de = {
  'myDog': "MY DOG",
  'firstSliderHeading': "Trainiere deinen Hund!",
  'firstSliderText':
      "Aufzeichnung von Trainingszeiten, Art der Übungen, Fortschritt und Leistungsbewertung. Aufzeichnung von Spaziergängen, Länge, Standort und zusätzlichen Anmerkungen.",
  'choosePageHeading': "WER BIST DU?",
  'dogsParent': "ELTERN DES HUNDES",
  'dogsExpert': "EXPERTE FÜR HUNDE",
  'setProfileExpert': "Profil einstellen",
  'uploadYourPhoto': "Laden Sie Ihr Foto hoch",
  'yourName': "Ihr Name",
  'typeYourname': "Geben Sie Ihren Namen hier ein",
  'dateOfBirth': "Geburtsdatum",
  'dateFormat': "TTMMJJJJ",
  'yourMail': "E-Mail",
  'typeYourMail': "Geben Sie Ihre E-Mail ein",
  'yourNumber': "Telefonnummer",
  'typeNumber': "Geben Sie Ihre Telefonnummer ein",
  'expertQualification': "Qualifikation",
  'typeQualification': "Ihre Qualifikation angeben",
  'expertSpeciality': "Spezialgebiet",
  'typeSpeciality': "Ihr Fachgebiet angeben",
  'yourPassword': "Passwort",
  'typePassword': "Geben Sie Ihr Passwort ein",
  'createButton': "Erstellen",
  'hey': "Hey! ",
  'welcome': "Willkommen bei ",
  'appointments': "Termine",
  'msgs': "Nachrichten",
  'reminders': "Erinnerungen",
  'seeProfile': "Profil anzeigen",
  'seeAll': "Alle anzeigen",
  'addDog': "Hund hinzufügen",
  'upcommingAppointments': "Bevorstehende Termine",
  'approved': "Genehmigt",
  'denied': "Abgelehnt",
  'dogName': "Name des Hundes",
  'time': "00:00 UHR",
  'home': "Startseite",
  'calendar': "Kalender",
  'settings': "Einstellungen",
  'vaccination': "Impfung",
  'medicine': "Medizin",
  'notifications': "Benachrichtigungen",
  'manageDogs': "Hunde verwalten",
  'giveFeedback': "Feedback geben",
  'termsOfUse': "Nutzungsbedingungen",
  'logout': "Ausloggen",
  'deleteAccount': "Konto löschen",
  'appointDetail': "Termin-Details",
  'edit': "Bearbeiten",
  'appointType': "Terminart",
  'pet': "Haustier",
  'date': "Datum",
  'notes': "Notizen",
  'dogNameH': "Hundename",
  'note':
      "Nach dieser Übung wird Ihr Hund mehr Aufmerksamkeit auf Sie und Ihre Hände richten.",
  'releaseDogData': "Geben Sie die Daten Ihres Hundes frei",
  'editRecord': "Datensatz bearbeiten",
  'shareRecord': "Datensatz teilen",
  'createRelease':
      "Erstellen und Freigeben der Daten Ihres Hundes für Experten",
  'nameCapital': "HUNDENAME",
  'data': "Daten",
  'profile': "Profil",
  'dogsData': "Hundedaten",
  'healthData': "Gesundheitsdaten",
  'healthSub':
      "Fügen Sie einen Termin zu den Gesundheitsdaten Ihres Hundes hinzu und setzen Sie eine Erinnerung für die Impfung oder die Pflegesitzung.",
  'appAppoint': "Termine hinzufügen",
  'exerciseExpert': "Übungen & Experten",
  'feedManage': "Futterverwaltung",
  'safetyEmergency': "Sicherheit und Notfall",
  'gotoCommunity': "Zur Community gehen",
  'kg': "00:00 KG",
  'weight': "Gewicht (Kg)",
  'filesFromExpert': "Freigegebene Dateien vom Experten",
  'releaseFiles': "Vom Experten freigegebene Datei nach dem Termin",
  'trainingStreak': "Trainingsbericht",
  'currentStreak': "Aktuelle Serie",
  'longestStreak': "Längste Serie",
  'timeTrained': "Trainierte Zeit",
  'days0': "0 Tage",
  'days1': "1 Tage",
  'timeStamp': "00:07:01",
  'microChipNum': "Mikrochip-Nummer",
  'gender': "Geschlecht",
  'breed': "Rasse",
  'editProfile': "Profil bearbeiten",
  'selectExpert': "Experten auswählen",
  'whoRU': "Wer bist du",
  'lookingFor': "Suchen Sie?",
  'trainExpert': "Trainingsexperte",
  'physioExpert': "Physiotherapeuten",
  'nutriExpert': "Ernährungsberater",
  'vetExpert': "Tierärzte",
  'otherExpert': "Andere",
  'selectReport': "Bericht auswählen",
  'whichRU': "Welchen Bericht möchten Sie",
  'wantRelease': "freigeben?",
  'trainReport': "Allgemeiner Bericht",
  'physioReport': "Ernährungsbericht",
  'nutriReport': "Trainingsbericht",
  'share': "Teilen",
  'selectExpertSingle': "Experten auswählen",
  'expertAbout':
      "Ein zertifizierter Hundetrainer mit jahrelanger Berufserfahrung, Gründer der Akademie für modernes Training für Hunde und Familien.",
  'trainingExpert': "Trainings-Experte",
  'healthExpert': "Gesundheitsexperte",
  'chat': "Chat",
  'relReport': "Bericht freigeben",
  'releasedReport': "Freigegebener Bericht",
  'seeProfileBtn': "Profil anzeigen",
  'endSharing': "Freigabe beenden",
  'wantToEdit': "MÖCHTEN SIE BEARBEITEN?",
  'dogBehaviour': "Verhalten des Hundes",
  'hintRecentDisease':
      "Geben Sie die kürzliche Krankheit Ihres Hundes ein, falls vorhanden",
  'hintDogBehaviour': "Wählen Sie das Verhalten Ihres Hundes aus",
  'photo': "Foto",
  'files': "Dateien",
  'save': "Speichern",
  'requests': "Anfragen/Termine",
  'underCare': "Hunde unter Ihrer Obhut",
  'requested': "Angefordert",
  'detail': "Detail",
  'reject': "Ablehnen",
  'approve': "Genehmigen",
  'completed': "Abgeschlossen",
  'createFile': "Hundendatei erstellen",
  'informParent':
      "Erstellen Sie eine Datei mit den Terminangaben des Hundes, um die Eltern dieses Hundes zu informieren.",
  'vaccinationReport': "Impfbericht",
  'typeVaccine': "Impfstofftyp",
  'selectVaccine': "Wählen Sie hier den Typ des Impfstoffs aus",
  'doze': "Dosis",
  'typeNotes': "Geben Sie hier einige Notizen ein",
  'sendNoti': "Benachrichtigung an Eltern senden",
  'release': "Freigeben",
  'typeDogName': "Geben Sie den Namen des Hundes hier ein",
  'timeHeading': "Zeit",
  'seePatients': "Patienten anzeigen",
  'makeAnnouncement': "Ankündigung machen",
  'trainingData': "Trainingsdaten",
  'seeTrainingFile': "Trainingsdatei anzeigen",
  'excercise': "Übung",
  'handFeeding': "Handfütterung",
  'title': "Titel",
  'description': "Beschreibung",
  'giveTitle': "Titel geben",
  'visibleToParent': "Sichtbar für Eltern",
  'addComment': "Kommentar hinzufügen",
  'patientFiles': "Patientenakten",
  'symptoms': "Symptome",
  'antiparasitic': "Antiparasitär",
  'vetVisit': "Tierarztbesuch",
  'seeAllFiles':
      "Alle Patientenakten anzeigen, die von Ihrem Experten freigegeben wurden.",
  'next': "Weiter",
  'lang': "Sprache",
  'sliderHeading2': "Gesundheitsdaten pflegen!",
  'sliderHeading3': "Mit Experten sprechen",
  'slidertxt2':
      "Sehen Sie Aufzeichnungen über vergangene und aktuelle Krankheiten, Medikamentenverabreichungen, Allergien und Operationen.",
  'slidertxt3':
      "Suchen und kontaktieren Sie Hundetrainer, Hundephysiotherapeuten, Hundenernährungsberater und Tierärzte.",
  'selectLang': "Sprache auswählen",
  'german': "Deutsch",
  'english': "Englisch",
  'french': "Französisch",
  'signupTxt':
      "Fast geschafft! Holen Sie das Beste aus MEINEM HUND heraus, indem Sie ein Konto erstellen. Verfolgen Sie Ihren Trainingsfortschritt, nehmen Sie an Herausforderungen teil, treffen Sie andere Hundebesitzer und vieles mehr!",
  'loginORsignup': "Einloggen oder registrieren",
  'login': "Anmelden",
  'google': "Mit Google fortfahren",
  'mail': "Mit E-Mail registrieren",
  'forgetPass': "Passwort vergessen?",
  'typeMail': "Geben Sie Ihre E-Mail-Adresse ein",
  'typePass': "Geben Sie Ihr Passwort ein",
  'alreadyAccount': "Sie haben bereits ein Konto?",
  'agreeing':
      "Indem Sie ein Konto erstellen, stimmen Sie den Datenschutzrichtlinien und Nutzungsbedingungen von MEIN HUND zu",
  'policy': "Datenschutzrichtlinien und Nutzungsbedingungen",
  'or': "ODER",
  'setProfile': "Profil für Ihren Hund festlegen",
  'uploadDog': "Foto des Hundes hochladen",
  'dogsName': "Name des Hundes",
  'neutered': "Kastriert",
  'color': "Farbe",
  'male': "Männlich",
  'female': "Weiblich",
  'typeGender': "Geschlecht Ihres Hundes beschreiben",
  'typeChipNumber': "Geben Sie die Chipnummer Ihres Hundes an",
  'typeColor': "Welche Farbe hat Ihr Hund?",
  'selectBreed': "Wählen Sie hier die Rasse Ihres Hundes aus",
  'typeWeight': "Wie viel wiegt Ihr Hund?",
  'createTraining': "Training erstellen",
  'uploadPhoto': "Foto hochladen",
  'trainingTitle': "Titel des Trainings",
  'giveTraining': "Geben Sie diesem Training einen Titel",
  'shortNote': "Kurze Notiz eingeben",
  'trainingNote': "Notiz",
  'listDown': "Auflisten der benötigten Ausrüstung",
  'neededEquipment': "Benötigte Ausrüstung",
  'trainingLevel': "Trainingslevel",
  'eligibility': "Berechtigung",
  'category': "Kategorie",
  'hintEligibilty': "Spezifizieren Sie die Berechtigung für dieses Training",
  'trainLength': "Trainingsdauer",
  'uploadFiles': "Dateien hochladen",
  'media': "Medien",
  'post': "Veröffentlichen",
  'material': "Trainingsmaterial",
  'general': "Allgemein",
  'dayByday': "Tag für Tag",
  'giveDescription': "Beschreibung eingeben",
  'exercises': "Übungen",
  'games': "Spiele",
  'goodManners': "Gutes Benehmen",
  'trainingPrograms': "Trainingsprogramme",
  'addTraining': "Trainingsprogramm hinzufügen",
  'stopBitting': "Aufhören zu beißen",
  'theory': "Theorie",
  'payAttention': "Aufmerksamkeit schenken",
  'addExercise': "Übung hinzufügen",
  'walk': "Spaziergang",
  'addFood': "Essen hinzufügen",
  'dietPlan': "Diätplan",
  'foodManagement': "Ernährungsmanagement",
  'dailFoodReminders': "Tägliche Erinnerungen an das Futter",
  'planDogExperts': "Pläne von den Experten Ihres Hundes",
  'feedNote':
      "Fügen Sie die täglichen Fütterungszeiten Ihres Hundes hinzu, erstellen Sie Essenspläne und Diätpläne.",
  'handFeedNote':
      "Nach dieser Übung wird Ihr Hund mehr Aufmerksamkeit auf Sie und Ihre Hände richten. Lenken Sie die Aufmerksamkeit Ihres Hundes auf sich und zeigen Sie ihm einige besonders leckere Lebensmittel oder Leckerlis in Ihrer Hand.",
  'payAttenNote':
      "Bringen Sie Ihrem Hund bei, Ihnen Aufmerksamkeit zu schenken und Ihnen zuzuhören, wann immer Sie ihn rufen.",
  'bittingNote':
      "Bringen Sie Ihrem Hund bei, seine Impulse, Aufregung und den Drang, seinen Kiefer um alles zu wickeln, zu kontrollieren.",
  'dietNote':
      "Bringen Sie Ihrem Hund bei, seine Impulse, Aufregung und den Drang, seinen Kiefer um alles zu wickeln, zu kontrollieren.",
  'morningFood': "Morgenfutter",
  'foodName': "Lebensmittelname",
  'eveningFood': "Abendessen",
  'typeFood': "Geben Sie den Lebensmittelnamen hier ein",
  'foodOutside': "Essen draußen",
  'reminderNoti': "Erinnerungsbenachrichtigung",
  'day': "Tag",
  'learnTennis': "Sie können alles über Tennis lernen.",
  'articles': "Artikel",
  'timing': "Timing",
  'duration': "Dauer",
  'calories': "Kalorien (kcal)",
  'createFoodorDiet': "Erstellen Sie einen Essens-/Diätplan",
  'createPlan': "Plan erstellen",
  'planTitle': "Plan-Titel",
  'startDate': "Startdatum",
  'endDate': "Enddatum",
  'givePlanTitle': "Geben Sie diesem Plan einen Titel",
  'createTimeTable': "Zeitplan erstellen",
  'createDetailedTb': "Detaillierten Zeitplan für diesen Plan erstellen",
  'seeEmergencyNum': "Notfallnummern anzeigen",
  'missingFound': "Vermisst & Gefunden",
  'missingNote':
      "Finden Sie Ihren vermissten Hund oder melden Sie einen gefundenen Hund, um jemandem zu helfen, sich mit seinem pelzigen Begleiter zu vereinen.",
  'addReport': "Bericht hinzufügen",
  'impInstructions': "Wichtige Anweisungen",
  'emergencyCases': "Was Sie in Notfällen tun müssen ",
  'inCaseEmergency': "Im Notfall",
  'noteEmergency':
      "Bringen Sie Ihrem Hund bei, seine Impulse, Aufregung und den Drang, seinen Kiefer um alles zu wickeln, zu kontrollieren.",
  'missingDog': "Vermisster Hund",
  'lostDate': "Verlorenes Datum",
  'lostAddress': "Verlorene Adresse",
  'foundedDog': "Gefundener Hund",
  'emergencyNums': "Notfallnummern",
  'search': "Suche",
  'addNum': "Nummer hinzufügen",
  'upload': "Hochladen",
  'typeName': "Name hier eingeben",
  'typeNum': "Telefonnummer hier eingeben",
  'name': "Name",
  'emergencyReport': "Notfallbericht",
  'whatYou': "Was möchten Sie",
  'wantTo': "melden?",
  'dogBait': "Hundeköder",
  'missingReport': "Vermisstenbericht",
  'foundOne': "Gefunden",
  'warnParents': "Eltern warnen vor",
  'theDanger': "der Gefahr",
  'baitLocation': "Köderort",
  'typeBaitLocation': "Köderort eingeben",
  'addBaitLocation': "Köderort auf Karte hinzufügen",
  'sendNotiAll': "Benachrichtigung an alle senden",
  'mapView': "Kartenansicht",
  'missingDogs': "Vermisste Hunde",
  'foundedDogs': "Gefundene Hunde",
  'createReport': "Bericht erstellen",
  'age': "Alter",
  'parentsData': "Elterndaten",
  'yourAddress': "Ihre Adresse",
  'typeAddress': "Adresse hier eingeben",
  'foundDate': "Gefundenes Datum",
  'multiplePhotos': "Mehrere Fotos hochladen",
  'missingDogProfile': "Vermisster Hund",
  'seeMap': "Karte anzeigen",
  'chatParent': "Mit Eltern chatten",
  'shareDog': "Hundeprofil teilen",
  'address': "Adresse",
  'addressHere': "Adresse hier",
  'parentName': "Elternname",
  'contactInfo': "Kontaktinformationen",
  'somePhotos': "Einige Fotos",
  'comments': "Kommentare",
  'commentTitle': "Kommentartitel",
  'management': "Verwaltung",
  'sendArchive': "In Archiv senden",
  'dontShow': "Nicht im Dashboard anzeigen",
  'deathDate': "Todesdatum",
  'deleteDog': "Hund löschen",
  'dogDied': "Hund ist verstorben",
  'reason': "Grund",
  'typeReason': "Grund hier eingeben",
  'otherReason': "Anderer Grund",
  'selectReason': "Grund auswählen",
  'whyReason': "Warum möchten Sie Ihren Hund löschen?",
  'lostNote':
      "Hallo! Ich habe meinen Hund verloren, bitte helfen Sie mir, meinen geliebten Hund zu finden. Danke",
  'missNote':
      "Hallo! Ich habe einen streunenden Hund gefunden. Bitte kontaktieren Sie mich, wenn jemand ihn erkennt.",
  'community': "Gemeinschaft",
  'chats': "Chats",
  'groups': "Gruppen",
  'connectExperts': "Mit Experten verbinden",
  'now': "jetzt",
  'bestWay': "Bester Weg, um den Hund zu trainieren",
  'addChat': "Chat hinzufügen",
  'online': "Online",
  'message': "Nachricht",
  'addNewGrps':
      "Neue Gruppe hinzufügen, indem Sie Gruppen erstellen oder finden",
  'newGroups': "Neue Gruppen",
  'findGroup': "Gruppe finden",
  'createGroup': "Gruppe erstellen",
  'eventCalendar': "Veranstaltungskalender",
  'addReminder': "Erinnerung hinzufügen",
  'reminderName': "Erinnerungsname",
  'repeat': "Wiederholen",
  'sett': "Setzen",
  'typeTime': "Zeit eingeben",
  'walkRouts': "Spaziergänge & Routen",
  'training': "Training",
  'experts': "Experten",
  'findExpert': "Experte finden",
  'availExperts': "Verfügbare Experten überprüfen und kontaktieren.",
  'find': "Finden",
  'yourDogExperts': "Ihre Hundesexperten",
  'addManual': "Manuell hinzufügen",
  'distance': "Entfernung (km)",
  'totalDistance': "Gesamtdistanz",
  'totalSteps': "Gesamtschritte",
  'minutes': "Minuten",
  'steps': "Schritte",
  'recentWalk': "Letzter Spaziergang",
  'addRecordManually': "Eintrag manuell hinzufügen",
  'swipe': "Zum Erfassen eines neuen Spaziergangs wischen",
  'walkRecord': "Spaziergangsaufzeichnung",
  'walkComplete': "Spaziergang abgeschlossen",
  'stops': "Stopps",
  'pause': "Pause",
  'complete': "Abgeschlossen",
  'comment': "Kommentar",
  'dogCondition': "Zustand des Hundes",
  'walkingTrack': "Spazierstrecke",
  'forest': "Wald",
  'weather': "Wie war das Wetter?",
  'warm': "Warm",
  'searchByName': "Nach Namen suchen",
  'sendInvite': "Einladung senden",
  'sendLocally':
      "Einladung lokal über Kommunikations-Apps oder über Nummer senden",
  'invite': "Einladung senden",
  'tutorial': "Tutorial",
  'completeExercise': "Übung abschließen",
  'details': "Details",
  'easy': "Einfach",
  'trainingLength': "Trainingsdauer",
  'equipment': "Ausrüstung",
  'editExercise': "Übung bearbeiten",
  'highFive': "High Five",
  'trainingNotes':
      "Nach dieser Übung wird Ihr Hund mehr Aufmerksamkeit auf Sie und Ihre Hände richten.",
  'trainingProgram': "Trainingsprogramm",
  'preparedByExpert': "Vorbereitet von einem Experten",
  'noAction': "Keine Aktion",
  'releasedReports': "Veröffentlichte Berichte",
  'expertProfile': "Expertenprofil",
  'sharedData': "Geteilte Daten",
  'totalTrainings': "Gesamttrainings",
  'saveRecord': "Aufzeichnung speichern",
  'caseOfEmergency': "Im Notfall",
  'success': "Erfolg",
  'loginMsg': "Jetzt können Sie sich anmelden",
  'error': "Fehler",
  'yes': "Ja",
  'no': "Nein",
  'addColor': "Farbe hinzufügen",
  'neuteredHint': "Ist Ihr Hund kastriert oder nicht",
  'pickColor': "Farbe wählen",
  'ok': "Ok",
  'more': "Mehr",
  'titleSelectBreed': "Rasse auswählen",
  'dogAdded': "Erfolgreich hinzugefügt",
  'dogdeleted': "Erfolgreich gelöscht",
  'fillAll': "Bitte füllen Sie alle Felder aus",
  'none': "Keine",
  'never': "Nie",
  'monday': "Montag",
  'tuesday': "Dienstag",
  'wednesday': "Mittwoch",
  'thursday': "Donnerstag",
  'friday': "Freitag",
  'saturday': "Samstag",
  'sunday': "Sonntag",
  'everyday': "Jeden Tag",
  'weekdays': "Wochentage",
  'weekend': "Wochenende",
  'setReminder': "Erinnerung einstellen",
  'signup': "Anmelden",
  'request': "Anfrage",
  'noAccount': "Sie haben kein Konto?",
  'incorrect': "E-Mail oder Passwort ist falsch",
  'selectImage': "Bitte Bild auswählen",
  'yourDoc': "Ihr Arzt",
  'selectDoc': "Arzt auswählen",
  'reasonAppointment': "Grund des Termins",
  'timeTable': "Zeitplan",
  'morning': "Morgen",
  'evening': "Abend",
  'midday': "Mittag",
  'quantity': "Menge (Gramm)",
  'selectRightTime': "Bitte wählen Sie die richtige Zeit",
  'morningTime': "9 Uhr bis 12 Uhr",
  'midTime': "12 Uhr bis 18 Uhr",
  'eveningTime': "18 Uhr bis Mitternacht",
  'addEvent': "Ereignis hinzufügen",
  'subTitle': "Untertitel",
  'giveSubTitle': "Untertitel angeben",
  'location': "Ort",
  'addLocation': "Ort hinzufügen",
};
