// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi7U7Hnp6i2jeqpsTm0_qPp_38iLfzpVM',
    appId: '1:556238993501:web:24e7867cfe9409f31fb5b4',
    messagingSenderId: '556238993501',
    projectId: 'my-dog-app-2db20',
    authDomain: 'my-dog-app-2db20.firebaseapp.com',
    storageBucket: 'my-dog-app-2db20.appspot.com',
    measurementId: 'G-PEQCZ6QFJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQhdzewsFtomZklvEGuw1KJigX9TE1hmk',
    appId: '1:556238993501:android:83942cba97ea14101fb5b4',
    messagingSenderId: '556238993501',
    projectId: 'my-dog-app-2db20',
    storageBucket: 'my-dog-app-2db20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrtSz7FNGd0x9Rp8T8I3WEvfk8mBlYavc',
    appId: '1:556238993501:ios:53e25fe7f00e41fd1fb5b4',
    messagingSenderId: '556238993501',
    projectId: 'my-dog-app-2db20',
    storageBucket: 'my-dog-app-2db20.appspot.com',
    iosBundleId: 'com.example.dogapp',
  );
}
