// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmFn7RztKPrClQ_YfVf9NOqtWDnuROepY',
    appId: '1:324124050894:web:a5fd2cfdeed16a2806d79f',
    messagingSenderId: '324124050894',
    projectId: 'dogplan-831c8',
    authDomain: 'dogplan-831c8.firebaseapp.com',
    storageBucket: 'dogplan-831c8.appspot.com',
    measurementId: 'G-Y97SW4JRHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbsOyn2hFmW2rfuXYFp4CG4YqQZ9NPWC4',
    appId: '1:324124050894:android:99b38d4125f7a08506d79f',
    messagingSenderId: '324124050894',
    projectId: 'dogplan-831c8',
    storageBucket: 'dogplan-831c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIsfMZ0MzR3kmc1EFxFX5gagmYPMGXNxY',
    appId: '1:324124050894:ios:cbd280081b89e89506d79f',
    messagingSenderId: '324124050894',
    projectId: 'dogplan-831c8',
    storageBucket: 'dogplan-831c8.appspot.com',
    iosBundleId: 'com.example.dogapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIsfMZ0MzR3kmc1EFxFX5gagmYPMGXNxY',
    appId: '1:324124050894:ios:cbd280081b89e89506d79f',
    messagingSenderId: '324124050894',
    projectId: 'dogplan-831c8',
    storageBucket: 'dogplan-831c8.appspot.com',
    iosBundleId: 'com.example.dogapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmFn7RztKPrClQ_YfVf9NOqtWDnuROepY',
    appId: '1:324124050894:web:a0da34bf8198c4f406d79f',
    messagingSenderId: '324124050894',
    projectId: 'dogplan-831c8',
    authDomain: 'dogplan-831c8.firebaseapp.com',
    storageBucket: 'dogplan-831c8.appspot.com',
    measurementId: 'G-SMLSZR2H7W',
  );

}